name: Build and Push Docker to ECR
on:
  push:
    branches:
      - main
      - '*'
jobs:
 # build:
  #  name: Build Docker Image
   # runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/main'
    #steps:
     # - name: Check out the repo
      #  uses: actions/checkout@v4
        
     # - name: Build Docker Image
      #  run: | 
           
           
           
  push_to_registry:
    name: Push Docker image to ECR
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: Push Docker image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
          rev=$(git rev-parse --short HEAD)
          docker build . -t 2039-ppe
          docker tag 2039-ppe 244530008913.dkr.ecr.eu-west-1.amazonaws.com/2039-ecr-repo:$rev
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/2039-ecr-repo:$rev